# Generated by Django 4.0.1 on 2022-01-28 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_student_facebook_student_instagram_student_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='about',
            field=models.TextField(blank=True, verbose_name='About'),
        ),
    ]
