# Generated by Django 4.0.1 on 2022-03-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_student_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Is Staff'),
        ),
    ]
