# Generated by Django 4.0.1 on 2022-02-17 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0003_student_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('picture', models.ImageField(upload_to='book', verbose_name='Photo')),
                ('desc', models.TextField(verbose_name='Description')),
                ('author', models.TextField(null=True, verbose_name='Author')),
                ('pub_year', models.IntegerField(null=True, verbose_name='Year published')),
                ('book_edition', models.IntegerField(null=True, verbose_name='Book_edition')),
                ('dept', models.TextField(null=True, verbose_name='Department ')),
                ('sem', models.IntegerField(null=True, verbose_name='Semester')),
                ('roll_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.student')),
            ],
        ),
    ]
