# Generated by Django 4.0.1 on 2022-02-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='to_lend',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
    ]
