# Generated by Django 4.0.1 on 2022-02-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_book_to_lend'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Posted'),
        ),
    ]
