# Generated by Django 4.0.1 on 2022-02-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_book_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_posted',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Date Posted'),
        ),
    ]
