# Generated by Django 4.0.1 on 2022-03-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_book_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Is verified'),
        ),
    ]
