# Generated by Django 4.0.1 on 2022-03-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_book_date_verified_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[(1, 'given'), (0, 'not given')], max_length=10, null=True, verbose_name='Status'),
        ),
    ]
