# Generated by Django 4.0.1 on 2022-03-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='date_given',
            field=models.DateTimeField(null=True, verbose_name='Date Given/Rejected'),
        ),
    ]
