# Generated by Django 4.0.1 on 2022-03-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='date_given',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Given/Rejected'),
        ),
    ]
