# Generated by Django 3.2.12 on 2022-03-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_alter_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_verified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date verified'),
        ),
    ]
